site_name: framaRAMA
docs_dir: docs/en
repo_url: https://github.com/framaRAMA/framarama
markdown_extensions:
  - attr_list
theme:
  logo: assets/logo.png
  favicon: assets/favicon.ico
  name: material
  features:
    - navigation.tabs

nav:
  - 'Introduction':
    - 'index.md'
    - 'architecture.md'
    - 'install.md'
  - 'config.md'
  - 'Server':
    - 'server/index.md'
    - 'server/frames.md'
    - 'server/displays.md'
    - 'Plugins':
      - 'server/plugins.md'
      - 'server/plugins/source.md'
      - 'server/plugins/sorting.md'
      - 'server/plugins/finishing.md'
      - 'server/plugins/context.md'
  - 'Frontend':
    - 'frontend/index.md'
  - 'Development':
    - 'development/index.md'
    - 'development/software.md'
    - 'development/documentation.md'
  - 'changelog.md'

