# Generated by Django 4.0.4 on 2022-07-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('local', 'Local setup'), ('cloud', 'Cloud setup')], help_text='Setup mode for frontend', max_length=32, verbose_name='Mode')),
                ('local_db_type', models.CharField(blank=True, choices=[('local', 'Local setup (skip database config)'), ('mysql', 'MySQL/MariaDB server')], help_text='Select type of database', max_length=16, null=True, verbose_name='Database type')),
                ('local_db_host', models.CharField(blank=True, help_text='Use external database server instead of local one', max_length=64, null=True, verbose_name='Database server')),
                ('local_db_name', models.CharField(blank=True, help_text='Put tables into the existing database', max_length=64, null=True, verbose_name='Database name')),
                ('local_db_user', models.CharField(blank=True, help_text='Use this username when connecting to database', max_length=64, null=True, verbose_name='Database user')),
                ('local_db_pass', models.CharField(blank=True, help_text='The password for the database user', max_length=64, null=True, verbose_name='Database password')),
                ('cloud_server', models.CharField(help_text='Remove server URL', max_length=255, verbose_name='Server')),
                ('cloud_display_access_key', models.CharField(help_text='Access key for display', max_length=64, verbose_name='Display')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
