# Generated by Django 4.0.4 on 2022-09-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='cloud_display_access_key',
            field=models.CharField(blank=True, help_text='Access key for display', max_length=64, null=True, verbose_name='Display'),
        ),
        migrations.AlterField(
            model_name='config',
            name='local_db_type',
            field=models.CharField(blank=True, choices=[('local', 'Integrated database (no database config required)'), ('mysql', 'MySQL/MariaDB server')], help_text='Select type of database', max_length=16, null=True, verbose_name='Database type'),
        ),
    ]
