# Generated by Django 4.0.4 on 2022-10-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_config_cloud_display_access_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='count_items',
            field=models.IntegerField(default=0, help_text='Total amount of item currently in collection', verbose_name='Item count'),
        ),
        migrations.AddField(
            model_name='config',
            name='count_views',
            field=models.IntegerField(default=0, help_text='Total count of images shown on display', verbose_name='Views'),
        ),
    ]
