# Generated by Django 4.0.4 on 2022-10-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_config_count_items_config_count_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='date_app_startup',
            field=models.DateTimeField(help_text='Startup date of the system', null=True, verbose_name='Startup'),
        ),
        migrations.AddField(
            model_name='config',
            name='date_items_update',
            field=models.DateTimeField(help_text='The date when the list of items was updates the last time', null=True, verbose_name='Items update'),
        ),
    ]
