# Generated by Django 4.0.4 on 2022-11-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_config_cloud_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='count_items_keep',
            field=models.IntegerField(blank=True, help_text='Amount of item to keep and show preview in frontend (default 6)', null=True, verbose_name='Keep items'),
        ),
        migrations.AddField(
            model_name='config',
            name='watermark_scale',
            field=models.IntegerField(blank=True, help_text='Make watermark larger or smaller (default 2)', null=True, verbose_name='Watermark scale'),
        ),
        migrations.AddField(
            model_name='config',
            name='watermark_shift',
            field=models.IntegerField(blank=True, help_text='Amount to move water mark away from borders (default 10)', null=True, verbose_name='Watermark shift'),
        ),
        migrations.AddField(
            model_name='config',
            name='watermark_type',
            field=models.CharField(choices=[('none', 'Do not watermark items'), ('ribbon', 'Show ribbon at the corners'), ('hbars', 'Draw horizontal bars (top & botton)'), ('vbars', 'Draw vertical bars (left & right)')], default='ribbon', help_text='Amount of item to keep and show preview in frontend', max_length=32, verbose_name='Watermark type'),
        ),
    ]
