# Generated by Django 4.0.4 on 2023-01-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_config_count_items_keep_config_watermark_scale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='count_errors',
            field=models.IntegerField(default=0, help_text='Count of errors on image processing', verbose_name='Errors'),
        ),
    ]
