# Generated by Django 4.0.4 on 2023-01-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_config_count_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='sys_time_zone',
            field=models.CharField(blank=True, choices=[('local', 'Local setup'), ('cloud', 'Cloud setup')], help_text='The timezone to use for this device', max_length=32, null=True, verbose_name='Timezone'),
        ),
    ]
