# Generated by Django 4.0.4 on 2023-03-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_alter_config_sys_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='cloud_status_restriction',
            field=models.JSONField(blank=True, help_text='Define which status information will be submitted to server', max_length=64, null=True, verbose_name='Status reporting'),
        ),
    ]
