# Generated by Django 4.0.10 on 2023-11-11 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_config_cloud_status_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='app_update_check',
            field=models.DurationField(blank=True, choices=[(None, 'disabled'), (datetime.timedelta(0), 'use defaults'), (datetime.timedelta(days=1), 'daily'), (datetime.timedelta(days=7), 'weekly'), (datetime.timedelta(days=30), 'monthly')], help_text='Time interval for update check', null=True, verbose_name='Update check'),
        ),
        migrations.AddField(
            model_name='config',
            name='app_update_install',
            field=models.BooleanField(default=False, verbose_name='Install updates'),
        ),
    ]
