# Generated by Django 4.0.10 on 2023-11-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_config_app_update_check_config_app_update_install'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='app_update_check_date',
            field=models.DateTimeField(help_text='The date of the last update check', null=True, verbose_name='Update check date'),
        ),
        migrations.AddField(
            model_name='config',
            name='app_update_install_date',
            field=models.DateTimeField(help_text='The date of the last update install', null=True, verbose_name='Install updates date'),
        ),
    ]
