# Generated by Django 4.0.10 on 2023-11-17 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_config_app_update_check_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='app_update_install_hour',
            field=models.DurationField(blank=True, choices=[(None, 'anytime'), (datetime.timedelta(0), '00:00 - 01:59'), (datetime.timedelta(seconds=7200), '02:00 - 03:59'), (datetime.timedelta(seconds=14400), '04:00 - 05:59'), (datetime.timedelta(seconds=21600), '06:00 - 07:59'), (datetime.timedelta(seconds=28800), '08:00 - 09:59'), (datetime.timedelta(seconds=36000), '10:00 - 11:59'), (datetime.timedelta(seconds=43200), '12:00 - 13:59'), (datetime.timedelta(seconds=50400), '14:00 - 15:59'), (datetime.timedelta(seconds=57600), '16:00 - 17:59'), (datetime.timedelta(seconds=64800), '18:00 - 19:59'), (datetime.timedelta(seconds=72000), '20:00 - 21:59'), (datetime.timedelta(seconds=79200), '22:00 - 23:59')], help_text='Installation time range for updates', null=True, verbose_name='Install hour'),
        ),
    ]
