# Generated by Django 4.0.4 on 2022-07-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='device_height',
            field=models.IntegerField(blank=True, help_text='Display height in pixels.', null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='display',
            name='device_width',
            field=models.IntegerField(blank=True, help_text='Display width in pixels.', null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='display',
            name='time_change',
            field=models.TimeField(blank=True, help_text='Hour and minutes to show each image.', null=True, verbose_name='View'),
        ),
    ]
