# Generated by Django 4.0.4 on 2022-08-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_display_device_height_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custommodel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='shapemodel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='textmodel',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='finishing',
            name='plugin_config',
            field=models.TextField(blank=True, editable=False, help_text='Plugin settings in JSON structure', null=True, verbose_name='Plugin config'),
        ),
        migrations.AddField(
            model_name='sorting',
            name='plugin_config',
            field=models.TextField(blank=True, editable=False, help_text='Plugin settings in JSON structure', null=True, verbose_name='Plugin config'),
        ),
        migrations.AddField(
            model_name='sourcestep',
            name='plugin_config',
            field=models.TextField(blank=True, editable=False, help_text='Plugin settings in JSON structure', null=True, verbose_name='Plugin config'),
        ),
    ]
