# Generated by Django 4.0.4 on 2022-08-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_custommodel_options_alter_shapemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='custommodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='shapemodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='textmodel',
            table=None,
        ),
    ]
