# Generated by Django 4.0.4 on 2022-09-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_custommodel_table_alter_shapemodel_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datamodel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='httpmodel',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='finishing',
            name='plugin_config',
            field=models.JSONField(blank=True, editable=False, help_text='Plugin settings in JSON structure', null=True, verbose_name='Plugin config'),
        ),
        migrations.AlterField(
            model_name='sorting',
            name='plugin_config',
            field=models.JSONField(blank=True, editable=False, help_text='Plugin settings in JSON structure', null=True, verbose_name='Plugin config'),
        ),
        migrations.AlterField(
            model_name='sourcestep',
            name='plugin_config',
            field=models.JSONField(blank=True, editable=False, help_text='Plugin settings in JSON structure', null=True, verbose_name='Plugin config'),
        ),
        migrations.AlterModelTable(
            name='sorting',
            table='config_sorting',
        ),
    ]
