# Generated by Django 4.0.4 on 2022-09-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_datamodel_options_alter_httpmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datamodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='httpmodel',
            table=None,
        ),
    ]
