# Generated by Django 4.0.4 on 2022-10-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_alter_datamodel_table_alter_httpmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='version',
            field=models.IntegerField(default=0, help_text='The version number increasing on each update', verbose_name='Update version'),
        ),
        migrations.AddField(
            model_name='item',
            name='version',
            field=models.IntegerField(default=0, help_text='The version number increasing on each update', verbose_name='Update version'),
        ),
    ]
