# Generated by Django 4.0.4 on 2022-10-20 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_frame_version_item_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeModel',
            fields=[
                ('finishing_ptr', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, primary_key=True, serialize=False, to='config.finishing')),
                ('alignment', models.CharField(help_text='Align images as selected when merging', max_length=32, verbose_name='Alignment')),
            ],
            options={
                'managed': False,
            },
            bases=('config.finishing',),
        ),
        migrations.CreateModel(
            name='ResizeModel',
            fields=[
                ('finishing_ptr', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, primary_key=True, serialize=False, to='config.finishing')),
                ('resize_x', models.CharField(help_text='Resize to given image width', max_length=64, verbose_name='X resizing')),
                ('resize_y', models.CharField(help_text='Resize to given image height', max_length=64, verbose_name='Y resizing')),
                ('keep_aspect', models.BooleanField(help_text='Resize only to given size as maximum while keeping aspect ratio', verbose_name='Keep aspect ratio')),
            ],
            options={
                'managed': False,
            },
            bases=('config.finishing',),
        ),
        migrations.CreateModel(
            name='TransformModel',
            fields=[
                ('finishing_ptr', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, primary_key=True, serialize=False, to='config.finishing')),
                ('mode', models.CharField(help_text='The transformation to apply', max_length=32, verbose_name='Type')),
                ('factor', models.CharField(help_text='Factor to apply (>1/<1 for blur/sharpen, percent for scale, degrees for rotate)', max_length=64, verbose_name='Factor')),
            ],
            options={
                'managed': False,
            },
            bases=('config.finishing',),
        ),
    ]
