# Generated by Django 4.0.4 on 2022-11-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_remove_datamodel_sourcestep_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishing',
            name='stroke_width',
            field=models.IntegerField(blank=True, help_text='The width to use when drawing lines', null=True, verbose_name='Line width'),
        ),
    ]
