# Generated by Django 4.0.4 on 2022-12-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_finishing_stroke_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='map_item_meta',
            field=models.TextField(blank=True, default='', help_text='When more fields should be mapped add them line by line (format: "&lt;target-name&gt;=&lt;source-name&gt;\\n")', verbose_name='Additional fields'),
        ),
    ]
