# Generated by Django 4.0.4 on 2022-12-26 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_alter_source_map_item_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.IntegerField(blank=True, help_text='The uptime of the device in milli seconds', null=True, verbose_name='Update')),
                ('memory_used', models.IntegerField(blank=True, help_text='Amount of memory currently in use', null=True, verbose_name='Memory used')),
                ('memory_free', models.IntegerField(blank=True, help_text='Amount of memory currently available', null=True, verbose_name='Memory available')),
                ('cpu_load', models.FloatField(blank=True, help_text='Current load of CPU', null=True, verbose_name='CPU load')),
                ('cpu_temp', models.IntegerField(blank=True, help_text='Current temperature of CPU', null=True, verbose_name='CPU temperature')),
                ('disk_data_free', models.IntegerField(blank=True, help_text='Available amount of space in data partition', null=True, verbose_name='Disk DATA free')),
                ('disk_tmp_free', models.IntegerField(blank=True, help_text='Available amount of space in temporary partition', null=True, verbose_name='Disk TMP free')),
                ('network_profile', models.CharField(blank=True, help_text='The name of the network profile currently in use', max_length=32, null=True, verbose_name='Network profile')),
                ('network_connected', models.IntegerField(blank=True, help_text='Time when the network connection was established', null=True, verbose_name='Network connected')),
                ('network_address_ip', models.CharField(blank=True, help_text='The network address of device', max_length=64, null=True, verbose_name='Network device IP')),
                ('network_address_gateway', models.CharField(blank=True, help_text='The network address of gateway', max_length=64, null=True, verbose_name='Network gateway IP')),
                ('screen_on', models.BooleanField(blank=True, help_text='Status of screen (1 is on, 0 is off)', null=True, verbose_name='Screen status')),
                ('screen_width', models.IntegerField(blank=True, help_text='The actual width of screen in pixels', null=True, verbose_name='Screen width')),
                ('screen_height', models.IntegerField(blank=True, help_text='The actual height of screen in pixels', null=True, verbose_name='Screen height')),
                ('items_total', models.IntegerField(blank=True, help_text='Total amount of items currently in use', null=True, verbose_name='Items total')),
                ('items_shown', models.IntegerField(blank=True, help_text='Total amount of items shown', null=True, verbose_name='Items shown')),
                ('items_updated', models.IntegerField(blank=True, help_text='Time of the last item list update', null=True, verbose_name='Items updated')),
                ('items_latest', models.CharField(blank=True, help_text='List of last items shown', max_length=255, null=True, verbose_name='Latest items')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='config.display')),
            ],
            options={
                'db_table': 'config_display_status',
                'ordering': ['-created'],
            },
        ),
    ]
