# Generated by Django 4.0.4 on 2022-12-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_displaystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaystatus',
            name='items_updated',
            field=models.DateTimeField(blank=True, help_text='Time of the last item list update', null=True, verbose_name='Items updated'),
        ),
        migrations.AlterField(
            model_name='displaystatus',
            name='network_connected',
            field=models.DateTimeField(blank=True, help_text='Time when the network connection was established', null=True, verbose_name='Network connected'),
        ),
    ]
