# Generated by Django 4.0.4 on 2022-12-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_remove_displaystatus_items_latest_displayitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaystatus',
            name='app_branch',
            field=models.CharField(blank=True, help_text='Branch of current version in use', max_length=64, null=True, verbose_name='Application branch'),
        ),
        migrations.AddField(
            model_name='displaystatus',
            name='app_date',
            field=models.DateTimeField(blank=True, help_text='Date of current version in use', null=True, verbose_name='Application date'),
        ),
        migrations.AddField(
            model_name='displaystatus',
            name='app_hash',
            field=models.CharField(blank=True, help_text='Commit hash of current version in use', max_length=48, null=True, verbose_name='Application hash'),
        ),
    ]
