# Generated by Django 4.0.4 on 2022-12-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_displaystatus_app_branch_displaystatus_app_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaystatus',
            name='disk_data_free',
            field=models.BigIntegerField(blank=True, help_text='Available amount of space in data partition', null=True, verbose_name='Disk DATA free'),
        ),
        migrations.AlterField(
            model_name='displaystatus',
            name='disk_tmp_free',
            field=models.BigIntegerField(blank=True, help_text='Available amount of space in temporary partition', null=True, verbose_name='Disk TMP free'),
        ),
        migrations.AlterField(
            model_name='displaystatus',
            name='memory_free',
            field=models.BigIntegerField(blank=True, help_text='Amount of memory currently available', null=True, verbose_name='Memory available'),
        ),
        migrations.AlterField(
            model_name='displaystatus',
            name='memory_used',
            field=models.BigIntegerField(blank=True, help_text='Amount of memory currently in use', null=True, verbose_name='Memory used'),
        ),
        migrations.AlterField(
            model_name='displaystatus',
            name='uptime',
            field=models.BigIntegerField(blank=True, help_text='The uptime of the device in milli seconds', null=True, verbose_name='Update'),
        ),
    ]
