# Generated by Django 4.0.4 on 2023-01-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_alter_displayitem_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishing',
            name='color_alpha',
        ),
        migrations.RemoveField(
            model_name='finishing',
            name='color_fill',
        ),
        migrations.RemoveField(
            model_name='finishing',
            name='color_stroke',
        ),
        migrations.RemoveField(
            model_name='finishing',
            name='stroke_width',
        ),
    ]
