# Generated by Django 4.0.4 on 2023-02-11 19:22

import config.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0021_remove_finishing_color_alpha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(help_text='The category of the type of data item', max_length=255, verbose_name='Category')),
                ('data_file', models.FileField(blank=True, editable=False, help_text='Store content in the filesystem', null=True, upload_to=config.models.Data._path, verbose_name='Save as file')),
                ('data_json', models.JSONField(blank=True, editable=False, help_text='The data object of this item', null=True, verbose_name='Save as JSON')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisplayItemThumbnailData',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('config.data',),
        ),
        migrations.CreateModel(
            name='ItemThumbnailData',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('config.data',),
        ),
        migrations.AddField(
            model_name='displayitem',
            name='thumbnail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.displayitemthumbnaildata'),
        ),
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.itemthumbnaildata'),
        ),
    ]
