# Generated by Django 4.0.4 on 2023-02-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0022_data_displayitemthumbnaildata_itemthumbnaildata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_mime',
            field=models.CharField(blank=True, help_text='The content type of this data item', max_length=64, null=True, verbose_name='Mime type'),
        ),
        migrations.AddField(
            model_name='data',
            name='data_size',
            field=models.IntegerField(blank=True, help_text='Amount of bytes used for this data item', null=True, verbose_name='Size'),
        ),
    ]
