# Generated by Django 4.0.4 on 2023-02-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0023_data_data_mime_data_data_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='update_interval',
            field=models.DurationField(blank=True, help_text='Time interval to run an automatic update of items', null=True, verbose_name='Update interval'),
        ),
    ]
