# Generated by Django 4.0.4 on 2023-02-18 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0024_source_update_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('plugin', models.CharField(max_length=64)),
                ('plugin_config', models.JSONField(blank=True, editable=False, help_text='Plugin settings in JSON structure', null=True, verbose_name='Plugin config')),
                ('ordering', models.IntegerField()),
                ('name', models.CharField(help_text='Name to access the context data (use lowercase and single word)', max_length=255, verbose_name='Name')),
                ('enabled', models.BooleanField(verbose_name='Enabled')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='config.frame')),
            ],
            options={
                'db_table': 'config_frame_context',
                'ordering': ['ordering'],
            },
        ),
    ]
