# Generated by Django 4.0.4 on 2023-03-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0025_framecontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='update_status',
            field=models.CharField(help_text='Result status information of last update process', max_length=256, null=True, verbose_name='Update status'),
        ),
        migrations.AlterField(
            model_name='source',
            name='update_error',
            field=models.CharField(help_text='Errors of last update process', max_length=256, null=True, verbose_name='Update error'),
        ),
    ]
