# Generated by Django 4.0.4 on 2023-03-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0026_source_update_status_alter_source_update_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseImageData',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('config.data',),
        ),
        migrations.AddField(
            model_name='data',
            name='meta',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Meta information for data item', null=True, verbose_name='Info'),
        ),
    ]
