# Generated by Django 4.0.4 on 2023-03-31 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0028_initial_data_meta_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='update_interval',
            field=models.DurationField(blank=True, choices=[(None, 'no automatic update'), (datetime.timedelta(0), 'use defaults'), (datetime.timedelta(seconds=900), 'each 15 minutes'), (datetime.timedelta(seconds=3600), 'each hour'), (datetime.timedelta(days=1), 'once a day')], help_text='Time interval to run an automatic update of items', null=True, verbose_name='Update interval'),
        ),
    ]
