# Generated by Django 4.0.10 on 2023-11-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0031_displaystatus_app_uptime_alter_displaystatus_uptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayitem',
            name='duration_download',
            field=models.IntegerField(blank=True, help_text='Duration in seconds used for downloading', null=True, verbose_name='Download duration'),
        ),
        migrations.AddField(
            model_name='displayitem',
            name='duration_finishing',
            field=models.IntegerField(blank=True, help_text='Duration in seconds used for finishing', null=True, verbose_name='Finishing duration'),
        ),
    ]
