# Generated by Django 4.2.14 on 2024-08-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0033_finishing_depth_finishing_lft_finishing_rgt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaystatus',
            name='container_name',
            field=models.CharField(blank=True, help_text='Container running Django WSGI application', max_length=32, null=True, verbose_name='Container'),
        ),
        migrations.AddField(
            model_name='displaystatus',
            name='container_version',
            field=models.CharField(blank=True, help_text='Version of WSGI container', max_length=32, null=True, verbose_name='Container'),
        ),
        migrations.AddField(
            model_name='displaystatus',
            name='django_version',
            field=models.CharField(blank=True, help_text='Django version running application', max_length=32, null=True, verbose_name='Django version'),
        ),
        migrations.AddField(
            model_name='displaystatus',
            name='python_version',
            field=models.CharField(blank=True, help_text='Version of python in use', max_length=32, null=True, verbose_name='Python version'),
        ),
        migrations.AddField(
            model_name='displaystatus',
            name='os_dist',
            field=models.CharField(blank=True, help_text='Distribution of installed operating system', max_length=32, null=True, verbose_name='Operating system distribution'),
        ),
        migrations.AddField(
            model_name='displaystatus',
            name='os_name',
            field=models.CharField(blank=True, help_text='Name of installed operating system', max_length=64, null=True, verbose_name='Operating system'),
        ),
        migrations.AddField(
            model_name='displaystatus',
            name='os_version',
            field=models.CharField(blank=True, help_text='Version of operating system', max_length=32, null=True, verbose_name='Operating system version'),
        ),
    ]
