# Generated by Django 4.2.15 on 2025-02-08 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0034_displaystatus_container_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=64)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='All properties as key/value pairs in JSON structure', null=True, verbose_name='List of properties')),
                ('name', models.CharField(help_text='Name of group of settings', max_length=255, verbose_name='Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'config_settings',
                'ordering': ['category', 'name'],
            },
        ),
    ]
