# Generated by Django 4.2.20 on 2025-12-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0036_source_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayitem',
            name='count_error',
            field=models.IntegerField(default=0, help_text='Count of errors while finishing', verbose_name='Errors'),
        ),
        migrations.AddField(
            model_name='displayitem',
            name='date_last_error',
            field=models.DateTimeField(blank=True, help_text='Date of the last error while finishing', null=True, verbose_name='Last error date'),
        ),
        migrations.AddField(
            model_name='displayitem',
            name='error_message',
            field=models.CharField(blank=True, help_text='Text of last error message', max_length=64, null=True, verbose_name='Error message'),
        ),
        migrations.AlterField(
            model_name='displayitem',
            name='count_hit',
            field=models.IntegerField(default=0, help_text='Amount of hits for this item', verbose_name='Hits'),
        ),
    ]
